// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectForge.Infrastructure.Data;

#nullable disable

namespace ProjectForge.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260608203712_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectForge.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GitHubId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GitHubId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.DesignPatternEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Architecture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImplementationNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LibraryRecommendationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScaffoldCommandsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LibraryRecommendationId");

                    b.ToTable("DesignPatterns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Architecture = "DotNet",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Abstrae el acceso a datos detrás de interfaces, facilitando testing y mantenimiento.",
                            Name = "Repository Pattern",
                            Pattern = "Repository"
                        },
                        new
                        {
                            Id = 2,
                            Architecture = "DotNet",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Separa las operaciones de lectura (Queries) de las de escritura (Commands).",
                            Name = "CQRS",
                            Pattern = "CQRS"
                        },
                        new
                        {
                            Id = 3,
                            Architecture = "DotNet",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Arquitectura en capas concéntricas con dependencias hacia el centro.",
                            Name = "Clean Architecture",
                            Pattern = "CleanArchitecture"
                        },
                        new
                        {
                            Id = 4,
                            Architecture = "DotNet",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Reduce el acoplamiento directo entre componentes usando un mediador.",
                            Name = "Mediator",
                            Pattern = "Mediator"
                        },
                        new
                        {
                            Id = 5,
                            Architecture = "Python",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Patrón de repositorio adaptado para Python/FastAPI.",
                            Name = "Repository Pattern",
                            Pattern = "Repository"
                        },
                        new
                        {
                            Id = 6,
                            Architecture = "JavaScript",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Arquitectura de microservicios para aplicaciones Node.js.",
                            Name = "Microservices",
                            Pattern = "Microservices"
                        });
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.LibraryRecommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Architecture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Framework")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstallCommand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PopularityScore")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Libraries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Architecture = "DotNet",
                            Category = "CQRS/Mediator",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Implementación del patrón Mediator para CQRS",
                            Framework = "AspNetCoreWebApi",
                            InstallCommand = "dotnet add package MediatR",
                            Name = "MediatR",
                            PackageName = "MediatR",
                            PopularityScore = 95
                        },
                        new
                        {
                            Id = 2,
                            Architecture = "DotNet",
                            Category = "ORM",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "ORM oficial de Microsoft para .NET",
                            Framework = "AspNetCoreWebApi",
                            InstallCommand = "dotnet add package Microsoft.EntityFrameworkCore",
                            Name = "Entity Framework Core",
                            PackageName = "Microsoft.EntityFrameworkCore",
                            PopularityScore = 99
                        },
                        new
                        {
                            Id = 3,
                            Architecture = "DotNet",
                            Category = "Validation",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Validación fluida y expresiva",
                            InstallCommand = "dotnet add package FluentValidation.AspNetCore",
                            Name = "FluentValidation",
                            PackageName = "FluentValidation.AspNetCore",
                            PopularityScore = 92
                        },
                        new
                        {
                            Id = 4,
                            Architecture = "DotNet",
                            Category = "Logging",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Logging estructurado para .NET",
                            InstallCommand = "dotnet add package Serilog.AspNetCore",
                            Name = "Serilog",
                            PackageName = "Serilog.AspNetCore",
                            PopularityScore = 97
                        },
                        new
                        {
                            Id = 5,
                            Architecture = "DotNet",
                            Category = "Mapping",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mapeo automático entre objetos",
                            InstallCommand = "dotnet add package AutoMapper",
                            Name = "AutoMapper",
                            PackageName = "AutoMapper",
                            PopularityScore = 94
                        },
                        new
                        {
                            Id = 6,
                            Architecture = "DotNet",
                            Category = "Documentation",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Generación automática de documentación OpenAPI",
                            Framework = "AspNetCoreWebApi",
                            InstallCommand = "dotnet add package Swashbuckle.AspNetCore",
                            Name = "Swashbuckle (Swagger)",
                            PackageName = "Swashbuckle.AspNetCore",
                            PopularityScore = 98
                        },
                        new
                        {
                            Id = 7,
                            Architecture = "DotNet",
                            Category = "Testing",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Framework de testing unitario para .NET",
                            InstallCommand = "dotnet add package xunit",
                            Name = "xUnit",
                            PackageName = "xunit",
                            PopularityScore = 96
                        },
                        new
                        {
                            Id = 8,
                            Architecture = "Python",
                            Category = "ORM",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "ORM más popular para Python",
                            InstallCommand = "pip install sqlalchemy",
                            Name = "SQLAlchemy",
                            PackageName = "sqlalchemy",
                            PopularityScore = 98
                        },
                        new
                        {
                            Id = 9,
                            Architecture = "Python",
                            Category = "Validation",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Validación de datos con type hints",
                            InstallCommand = "pip install pydantic",
                            Name = "Pydantic",
                            PackageName = "pydantic",
                            PopularityScore = 97
                        },
                        new
                        {
                            Id = 10,
                            Architecture = "Python",
                            Category = "Migrations",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Migraciones de base de datos para SQLAlchemy",
                            InstallCommand = "pip install alembic",
                            Name = "Alembic",
                            PackageName = "alembic",
                            PopularityScore = 90
                        });
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneratedReadme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepositoryUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WizardConfigId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WizardConfigId")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.ProjectLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommandExecuted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("int");

                    b.Property<bool>("IsError")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectLogs");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.ProjectTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Architecture")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Database")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Framework")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Infrastructure")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VariablesSchemaJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Architecture", "TemplateType", "Database", "Infrastructure");

                    b.ToTable("Templates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Architecture = "DotNet",
                            Content = "FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base\nWORKDIR /app\nEXPOSE 8080\n\nFROM mcr.microsoft.com/dotnet/sdk:10.0 AS build\nWORKDIR /src\nCOPY . .\nRUN dotnet restore\nRUN dotnet publish -c Release -o /app/publish\n\nFROM base AS final\nWORKDIR /app\nCOPY --from=build /app/publish .\nENTRYPOINT [\"dotnet\", \"{{APP_NAME}}.dll\"]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Multi-stage Dockerfile para ASP.NET Core",
                            IsActive = true,
                            Name = "Dockerfile .NET",
                            TemplateType = "dockerfile",
                            Version = 1
                        },
                        new
                        {
                            Id = 2,
                            Architecture = "DotNet",
                            Content = "version: '3.9'\nservices:\n  app:\n    build: .\n    ports:\n      - \"{{APP_PORT}}:8080\"\n    environment:\n      - ConnectionStrings__Default=Host=db;Database={{DB_NAME}};Username=postgres;Password=secret\n    depends_on:\n      db:\n        condition: service_healthy\n\n  db:\n    image: postgres:16-alpine\n    environment:\n      POSTGRES_DB: {{DB_NAME}}\n      POSTGRES_PASSWORD: secret\n    ports:\n      - \"{{DB_PORT}}:5432\"\n    volumes:\n      - pgdata:/var/lib/postgresql/data\n    healthcheck:\n      test: [\"CMD\",\"pg_isready\",\"-U\",\"postgres\"]\n      interval: 10s\n      timeout: 5s\n      retries: 5\n\nvolumes:\n  pgdata:",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Database = "PostgreSQL",
                            Description = "Docker Compose para .NET + PostgreSQL",
                            Infrastructure = "DockerCompose",
                            IsActive = true,
                            Name = "Compose .NET + PostgreSQL",
                            TemplateType = "compose",
                            Version = 1
                        },
                        new
                        {
                            Id = 3,
                            Architecture = "DotNet",
                            Content = "version: '3.9'\nservices:\n  app:\n    build: .\n    ports:\n      - \"{{APP_PORT}}:8080\"\n    environment:\n      - ConnectionStrings__Default=Server=db;Database={{DB_NAME}};User=root;Password=secret;\n    depends_on:\n      db:\n        condition: service_healthy\n\n  db:\n    image: mysql:8.0\n    environment:\n      MYSQL_ROOT_PASSWORD: secret\n      MYSQL_DATABASE: {{DB_NAME}}\n    ports:\n      - \"{{DB_PORT}}:3306\"\n    volumes:\n      - mysqldata:/var/lib/mysql\n    healthcheck:\n      test: [\"CMD\",\"mysqladmin\",\"ping\",\"-h\",\"localhost\"]\n      interval: 10s\n      timeout: 5s\n      retries: 5\n\nvolumes:\n  mysqldata:",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Database = "MySQL",
                            Description = "Docker Compose para .NET + MySQL",
                            Infrastructure = "DockerCompose",
                            IsActive = true,
                            Name = "Compose .NET + MySQL",
                            TemplateType = "compose",
                            Version = 1
                        },
                        new
                        {
                            Id = 4,
                            Architecture = "DotNet",
                            Content = "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: {{APP_NAME}}\nspec:\n  replicas: 2\n  selector:\n    matchLabels:\n      app: {{APP_NAME}}\n  template:\n    metadata:\n      labels:\n        app: {{APP_NAME}}\n    spec:\n      containers:\n      - name: {{APP_NAME}}\n        image: {{APP_NAME}}:latest\n        ports:\n        - containerPort: 8080\n---\napiVersion: v1\nkind: Service\nmetadata:\n  name: {{APP_NAME}}-svc\nspec:\n  selector:\n    app: {{APP_NAME}}\n  ports:\n  - port: 80\n    targetPort: 8080\n  type: LoadBalancer",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kubernetes Deployment para la aplicación",
                            Infrastructure = "Kubernetes",
                            IsActive = true,
                            Name = "K8s App Deployment",
                            TemplateType = "k8s-deployment",
                            Version = 1
                        },
                        new
                        {
                            Id = 5,
                            Architecture = "DotNet",
                            Content = "[Dd]ebug/\n[Rr]elease/\n[Bb]in/\n[Oo]bj/\n*.user\n*.suo\n*.vs/\n.vscode/\n.env\n.env.*\n*.pfx\npackages/",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gitignore para proyectos .NET",
                            IsActive = true,
                            Name = ".gitignore .NET",
                            TemplateType = "gitignore",
                            Version = 1
                        },
                        new
                        {
                            Id = 6,
                            Architecture = "DotNet",
                            Content = "name: CI/CD\non:\n  push:\n    branches: [main]\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n    - uses: actions/checkout@v4\n    - uses: actions/setup-dotnet@v4\n      with:\n        dotnet-version: '10.0.x'\n    - run: dotnet restore\n    - run: dotnet build --no-restore\n    - run: dotnet test --no-build",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pipeline CI/CD para .NET con GitHub Actions",
                            IsActive = true,
                            Name = "CI .NET GitHub Actions",
                            TemplateType = "ci",
                            Version = 1
                        });
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.VpsCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EncryptedPassword")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("PrivateKeyPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WizardConfigId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WizardConfigId");

                    b.ToTable("VpsCredentials");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.WizardConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalOptionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Architecture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Database")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeploymentTarget")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesignPatternsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Framework")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrameworkVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Infrastructure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LibrariesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("WizardConfigs");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.DesignPatternEntry", b =>
                {
                    b.HasOne("ProjectForge.Core.Entities.LibraryRecommendation", null)
                        .WithMany("SuggestedWithPatterns")
                        .HasForeignKey("LibraryRecommendationId");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.Project", b =>
                {
                    b.HasOne("ProjectForge.Core.Entities.ApplicationUser", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectForge.Core.Entities.WizardConfig", "WizardConfig")
                        .WithOne()
                        .HasForeignKey("ProjectForge.Core.Entities.Project", "WizardConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WizardConfig");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.ProjectLog", b =>
                {
                    b.HasOne("ProjectForge.Core.Entities.Project", "Project")
                        .WithMany("Logs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.VpsCredential", b =>
                {
                    b.HasOne("ProjectForge.Core.Entities.WizardConfig", "WizardConfig")
                        .WithMany("VpsCredentials")
                        .HasForeignKey("WizardConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WizardConfig");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.LibraryRecommendation", b =>
                {
                    b.Navigation("SuggestedWithPatterns");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.Project", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.WizardConfig", b =>
                {
                    b.Navigation("VpsCredentials");
                });
#pragma warning restore 612, 618
        }
    }
}
