// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ProjectForge.Infrastructure.Data;

#nullable disable

namespace ProjectForge.Infrastructure.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260625210000_AddPhpSeedData")]
partial class AddPhpSeedData
{
}
