// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectForge.Infrastructure.Data;

#nullable disable

namespace ProjectForge.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260626022308_AddNestJsCqrsSupport")]
    partial class AddNestJsCqrsSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectForge.Core.Entities.AiSuggestionCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CacheKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LibrariesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatternsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CacheKey")
                        .IsUnique();

                    b.ToTable("AiSuggestionCaches");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GitHubId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GitHubId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.DesignPatternEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Architecture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImplementationNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LibraryRecommendationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScaffoldCommandsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LibraryRecommendationId");

                    b.ToTable("DesignPatterns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Architecture = "DotNet",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Abstrae el acceso a datos detrás de interfaces, facilitando testing y mantenimiento.",
                            Name = "Repository Pattern",
                            Pattern = "Repository"
                        },
                        new
                        {
                            Id = 2,
                            Architecture = "DotNet",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Separa las operaciones de lectura (Queries) de las de escritura (Commands).",
                            Name = "CQRS",
                            Pattern = "CQRS"
                        },
                        new
                        {
                            Id = 3,
                            Architecture = "DotNet",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Arquitectura en capas concéntricas con dependencias hacia el centro.",
                            Name = "Clean Architecture",
                            Pattern = "CleanArchitecture"
                        },
                        new
                        {
                            Id = 4,
                            Architecture = "DotNet",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Reduce el acoplamiento directo entre componentes usando un mediador.",
                            Name = "Mediator",
                            Pattern = "Mediator"
                        },
                        new
                        {
                            Id = 5,
                            Architecture = "Python",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Patrón de repositorio adaptado para Python/FastAPI.",
                            Name = "Repository Pattern",
                            Pattern = "Repository"
                        },
                        new
                        {
                            Id = 19,
                            Architecture = "JavaScript",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Aisla el acceso a datos detras de un contrato y un repositorio concreto para Node.js.",
                            ImplementationNotes = "Crear src/domain, src/application, src/ports y src/infrastructure; registrar el repo en el contenedor de la app.",
                            Name = "Repository Pattern (Node.js)",
                            Pattern = "Repository",
                            ScaffoldCommandsJson = "[\"mkdir -p src/domain src/application src/ports src/infrastructure\"]"
                        },
                        new
                        {
                            Id = 20,
                            Architecture = "JavaScript",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Organiza Node.js en capas para mantener la logica de negocio fuera del framework.",
                            ImplementationNotes = "Separar src/domain, src/application, src/interfaces y src/infrastructure; exponer el punto de entrada en src/server.js.",
                            Name = "Clean Architecture (Node.js)",
                            Pattern = "CleanArchitecture",
                            ScaffoldCommandsJson = "[\"mkdir -p src/domain src/application src/interfaces src/infrastructure\"]"
                        },
                        new
                        {
                            Id = 21,
                            Architecture = "JavaScript",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Usa puertos y adaptadores para aislar el dominio en aplicaciones Node.js.",
                            ImplementationNotes = "Modelar puertos en src/ports y adaptadores en src/adapters; dejar el dominio libre de dependencias externas.",
                            Name = "Hexagonal Architecture (Node.js)",
                            Pattern = "HexagonalArchitecture",
                            ScaffoldCommandsJson = "[\"mkdir -p src/domain src/application src/ports src/adapters\"]"
                        },
                        new
                        {
                            Id = 22,
                            Architecture = "JavaScript",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Separa comandos y consultas para simplificar la evolucion del backend Node.js.",
                            ImplementationNotes = "Separar commands, queries y handlers en src/application; usar un bus ligero o funciones puras para coordinarlos.",
                            Name = "CQRS (JavaScript)",
                            Pattern = "CQRS",
                            ScaffoldCommandsJson = "[\"mkdir -p src/application/commands src/application/queries src/application/handlers\"]"
                        },
                        new
                        {
                            Id = 23,
                            Architecture = "JavaScript",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Centraliza la orquestacion de mensajes para reducir el acoplamiento entre handlers.",
                            ImplementationNotes = "Crear un mediador liviano en src/application y separar los mensajes en src/application/messages.",
                            Name = "Mediator (JavaScript)",
                            Pattern = "Mediator",
                            ScaffoldCommandsJson = "[\"mkdir -p src/application src/application/messages src/application/handlers\"]"
                        },
                        new
                        {
                            Id = 24,
                            Architecture = "JavaScript",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Divide la solucion en servicios Node.js desacoplados cuando existan limites claros de dominio.",
                            ImplementationNotes = "Separar src/services, src/events, src/workers y src/integrations; usar HTTP o colas para desacoplar.",
                            Name = "Microservices (JavaScript)",
                            Pattern = "Microservices",
                            ScaffoldCommandsJson = "[\"mkdir -p src/services src/events src/workers src/integrations\"]"
                        },
                        new
                        {
                            Id = 25,
                            Architecture = "JavaScript",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Implementa CQRS con el paquete oficial de NestJS usando CommandBus, QueryBus y EventBus.",
                            ImplementationNotes = "Crear módulos, comandos, consultas, eventos de dominio y handlers; registrar CqrsModule en el modulo raiz.",
                            Name = "CQRS (NestJS)",
                            Pattern = "CQRS",
                            ScaffoldCommandsJson = "[\"npm install @nestjs/cqrs\"]"
                        });
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.LibraryRecommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Architecture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Framework")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstallCommand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PopularityScore")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Libraries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Architecture = "DotNet",
                            Category = "CQRS/Mediator",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Implementación del patrón Mediator para CQRS",
                            Framework = "AspNetCoreWebApi",
                            InstallCommand = "dotnet add package MediatR",
                            Name = "MediatR",
                            PackageName = "MediatR",
                            PopularityScore = 95
                        },
                        new
                        {
                            Id = 2,
                            Architecture = "DotNet",
                            Category = "ORM",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "ORM oficial de Microsoft para .NET",
                            Framework = "AspNetCoreWebApi",
                            InstallCommand = "dotnet add package Microsoft.EntityFrameworkCore",
                            Name = "Entity Framework Core",
                            PackageName = "Microsoft.EntityFrameworkCore",
                            PopularityScore = 99
                        },
                        new
                        {
                            Id = 3,
                            Architecture = "DotNet",
                            Category = "Validation",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Validación fluida y expresiva",
                            InstallCommand = "dotnet add package FluentValidation.AspNetCore",
                            Name = "FluentValidation",
                            PackageName = "FluentValidation.AspNetCore",
                            PopularityScore = 92
                        },
                        new
                        {
                            Id = 4,
                            Architecture = "DotNet",
                            Category = "Logging",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Logging estructurado para .NET",
                            InstallCommand = "dotnet add package Serilog.AspNetCore",
                            Name = "Serilog",
                            PackageName = "Serilog.AspNetCore",
                            PopularityScore = 97
                        },
                        new
                        {
                            Id = 5,
                            Architecture = "DotNet",
                            Category = "Mapping",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mapeo automático entre objetos",
                            InstallCommand = "dotnet add package AutoMapper",
                            Name = "AutoMapper",
                            PackageName = "AutoMapper",
                            PopularityScore = 94
                        },
                        new
                        {
                            Id = 6,
                            Architecture = "DotNet",
                            Category = "Documentation",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Generación automática de documentación OpenAPI",
                            Framework = "AspNetCoreWebApi",
                            InstallCommand = "dotnet add package Swashbuckle.AspNetCore",
                            Name = "Swashbuckle (Swagger)",
                            PackageName = "Swashbuckle.AspNetCore",
                            PopularityScore = 98
                        },
                        new
                        {
                            Id = 7,
                            Architecture = "DotNet",
                            Category = "Testing",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Framework de testing unitario para .NET",
                            InstallCommand = "dotnet add package xunit",
                            Name = "xUnit",
                            PackageName = "xunit",
                            PopularityScore = 96
                        },
                        new
                        {
                            Id = 8,
                            Architecture = "Python",
                            Category = "ORM",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "ORM más popular para Python",
                            InstallCommand = "pip install sqlalchemy",
                            Name = "SQLAlchemy",
                            PackageName = "sqlalchemy",
                            PopularityScore = 98
                        },
                        new
                        {
                            Id = 9,
                            Architecture = "Python",
                            Category = "Validation",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Validación de datos con type hints",
                            InstallCommand = "pip install pydantic",
                            Name = "Pydantic",
                            PackageName = "pydantic",
                            PopularityScore = 97
                        },
                        new
                        {
                            Id = 10,
                            Architecture = "Python",
                            Category = "Migrations",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Migraciones de base de datos para SQLAlchemy",
                            InstallCommand = "pip install alembic",
                            Name = "Alembic",
                            PackageName = "alembic",
                            PopularityScore = 90
                        },
                        new
                        {
                            Id = 26,
                            Architecture = "JavaScript",
                            Category = "Configuration",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Carga variables de entorno desde archivos .env",
                            InstallCommand = "npm install dotenv",
                            Name = "dotenv",
                            PackageName = "dotenv",
                            PopularityScore = 99
                        },
                        new
                        {
                            Id = 27,
                            Architecture = "JavaScript",
                            Category = "HTTP Framework",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Framework minimalista y flexible para APIs Node.js",
                            Framework = "ExpressJs",
                            InstallCommand = "npm install express",
                            Name = "Express",
                            PackageName = "express",
                            PopularityScore = 98
                        },
                        new
                        {
                            Id = 28,
                            Architecture = "JavaScript",
                            Category = "Security",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cabeceras HTTP seguras para aplicaciones Node.js",
                            InstallCommand = "npm install helmet",
                            Name = "Helmet",
                            PackageName = "helmet",
                            PopularityScore = 94
                        },
                        new
                        {
                            Id = 29,
                            Architecture = "JavaScript",
                            Category = "Logging",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Logger HTTP simple para Express",
                            Framework = "ExpressJs",
                            InstallCommand = "npm install morgan",
                            Name = "Morgan",
                            PackageName = "morgan",
                            PopularityScore = 90
                        },
                        new
                        {
                            Id = 30,
                            Architecture = "JavaScript",
                            Category = "Configuration",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gestion de configuracion por entorno para NestJS",
                            Framework = "NestJs",
                            InstallCommand = "npm install @nestjs/config",
                            Name = "@nestjs/config",
                            PackageName = "@nestjs/config",
                            PopularityScore = 96
                        },
                        new
                        {
                            Id = 31,
                            Architecture = "JavaScript",
                            Category = "Validation",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Validacion declarativa basada en decoradores",
                            Framework = "NestJs",
                            InstallCommand = "npm install class-validator",
                            Name = "class-validator",
                            PackageName = "class-validator",
                            PopularityScore = 95
                        },
                        new
                        {
                            Id = 32,
                            Architecture = "JavaScript",
                            Category = "Documentation",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Generacion de OpenAPI y Swagger para NestJS",
                            Framework = "NestJs",
                            InstallCommand = "npm install @nestjs/swagger swagger-ui-express",
                            Name = "@nestjs/swagger",
                            PackageName = "@nestjs/swagger",
                            PopularityScore = 93
                        },
                        new
                        {
                            Id = 33,
                            Architecture = "JavaScript",
                            Category = "Authentication",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Autenticacion lista para Next.js",
                            Framework = "NextJs",
                            InstallCommand = "npm install next-auth",
                            Name = "NextAuth",
                            PackageName = "next-auth",
                            PopularityScore = 97
                        },
                        new
                        {
                            Id = 34,
                            Architecture = "JavaScript",
                            Category = "Validation",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Esquemas de validacion y parseo para Node y Next",
                            InstallCommand = "npm install zod",
                            Name = "Zod",
                            PackageName = "zod",
                            PopularityScore = 98
                        },
                        new
                        {
                            Id = 35,
                            Architecture = "JavaScript",
                            Category = "Data Fetching",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cache y sincronizacion de estado servidor para Next.js",
                            Framework = "NextJs",
                            InstallCommand = "npm install @tanstack/react-query",
                            Name = "React Query",
                            PackageName = "@tanstack/react-query",
                            PopularityScore = 92
                        },
                        new
                        {
                            Id = 36,
                            Architecture = "JavaScript",
                            Category = "CQRS",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "CommandBus, QueryBus y EventBus oficiales para NestJS",
                            Framework = "NestJs",
                            InstallCommand = "npm install @nestjs/cqrs",
                            Name = "@nestjs/cqrs",
                            PackageName = "@nestjs/cqrs",
                            PopularityScore = 97
                        });
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneratedReadme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepositoryUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WizardConfigId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WizardConfigId")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.ProjectLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommandExecuted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("int");

                    b.Property<bool>("IsError")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectLogs");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.ProjectTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Architecture")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Database")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Framework")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Infrastructure")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VariablesSchemaJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Architecture", "TemplateType", "Database", "Infrastructure");

                    b.ToTable("Templates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Architecture = "DotNet",
                            Content = "FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base\nWORKDIR /app\nEXPOSE 8080\n\nFROM mcr.microsoft.com/dotnet/sdk:10.0 AS build\nWORKDIR /src\nCOPY . .\nRUN dotnet restore\nRUN dotnet publish -c Release -o /app/publish\n\nFROM base AS final\nWORKDIR /app\nCOPY --from=build /app/publish .\nENTRYPOINT [\"dotnet\", \"{{APP_NAME}}.dll\"]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Multi-stage Dockerfile para ASP.NET Core",
                            IsActive = true,
                            Name = "Dockerfile .NET",
                            TemplateType = "dockerfile",
                            Version = 1
                        },
                        new
                        {
                            Id = 2,
                            Architecture = "DotNet",
                            Content = "version: '3.9'\nservices:\n  app:\n    build: .\n    ports:\n      - \"{{APP_PORT}}:8080\"\n    environment:\n      - ConnectionStrings__Default=Host=db;Database={{DB_NAME}};Username=postgres;Password=secret\n    depends_on:\n      db:\n        condition: service_healthy\n\n  db:\n    image: postgres:16-alpine\n    environment:\n      POSTGRES_DB: {{DB_NAME}}\n      POSTGRES_PASSWORD: secret\n    ports:\n      - \"{{DB_PORT}}:5432\"\n    volumes:\n      - pgdata:/var/lib/postgresql/data\n    healthcheck:\n      test: [\"CMD\",\"pg_isready\",\"-U\",\"postgres\"]\n      interval: 10s\n      timeout: 5s\n      retries: 5\n\nvolumes:\n  pgdata:",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Database = "PostgreSQL",
                            Description = "Docker Compose para .NET + PostgreSQL",
                            Infrastructure = "DockerCompose",
                            IsActive = true,
                            Name = "Compose .NET + PostgreSQL",
                            TemplateType = "compose",
                            Version = 1
                        },
                        new
                        {
                            Id = 3,
                            Architecture = "DotNet",
                            Content = "version: '3.9'\nservices:\n  app:\n    build: .\n    ports:\n      - \"{{APP_PORT}}:8080\"\n    environment:\n      - ConnectionStrings__Default=Server=db;Database={{DB_NAME}};User=root;Password=secret;\n    depends_on:\n      db:\n        condition: service_healthy\n\n  db:\n    image: mysql:8.0\n    environment:\n      MYSQL_ROOT_PASSWORD: secret\n      MYSQL_DATABASE: {{DB_NAME}}\n    ports:\n      - \"{{DB_PORT}}:3306\"\n    volumes:\n      - mysqldata:/var/lib/mysql\n    healthcheck:\n      test: [\"CMD\",\"mysqladmin\",\"ping\",\"-h\",\"localhost\"]\n      interval: 10s\n      timeout: 5s\n      retries: 5\n\nvolumes:\n  mysqldata:",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Database = "MySQL",
                            Description = "Docker Compose para .NET + MySQL",
                            Infrastructure = "DockerCompose",
                            IsActive = true,
                            Name = "Compose .NET + MySQL",
                            TemplateType = "compose",
                            Version = 1
                        },
                        new
                        {
                            Id = 4,
                            Architecture = "DotNet",
                            Content = "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: {{APP_NAME}}\nspec:\n  replicas: 2\n  selector:\n    matchLabels:\n      app: {{APP_NAME}}\n  template:\n    metadata:\n      labels:\n        app: {{APP_NAME}}\n    spec:\n      containers:\n      - name: {{APP_NAME}}\n        image: {{APP_NAME}}:latest\n        ports:\n        - containerPort: 8080\n---\napiVersion: v1\nkind: Service\nmetadata:\n  name: {{APP_NAME}}-svc\nspec:\n  selector:\n    app: {{APP_NAME}}\n  ports:\n  - port: 80\n    targetPort: 8080\n  type: LoadBalancer",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kubernetes Deployment para la aplicación",
                            Infrastructure = "Kubernetes",
                            IsActive = true,
                            Name = "K8s App Deployment",
                            TemplateType = "k8s-deployment",
                            Version = 1
                        },
                        new
                        {
                            Id = 5,
                            Architecture = "DotNet",
                            Content = "[Dd]ebug/\n[Rr]elease/\n[Bb]in/\n[Oo]bj/\n*.user\n*.suo\n*.vs/\n.vscode/\n.env\n.env.*\n*.pfx\npackages/",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gitignore para proyectos .NET",
                            IsActive = true,
                            Name = ".gitignore .NET",
                            TemplateType = "gitignore",
                            Version = 1
                        },
                        new
                        {
                            Id = 6,
                            Architecture = "DotNet",
                            Content = "name: CI/CD\non:\n  push:\n    branches: [main]\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n    - uses: actions/checkout@v4\n    - uses: actions/setup-dotnet@v4\n      with:\n        dotnet-version: '10.0.x'\n    - run: dotnet restore\n    - run: dotnet build --no-restore\n    - run: dotnet test --no-build",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pipeline CI/CD para .NET con GitHub Actions",
                            IsActive = true,
                            Name = "CI .NET GitHub Actions",
                            TemplateType = "ci",
                            Version = 1
                        },
                        new
                        {
                            Id = 14,
                            Architecture = "JavaScript",
                            Content = "FROM node:22-alpine\n\nWORKDIR /app\n\nCOPY package*.json ./\nRUN if [ -f package-lock.json ]; then npm ci --omit=dev; else npm install --omit=dev; fi\n\nCOPY . .\n\nEXPOSE 3000\n\nCMD [\"npm\", \"start\"]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dockerfile generico para Node.js, Express, NestJS y Next.js",
                            IsActive = true,
                            Name = "Dockerfile JavaScript",
                            TemplateType = "dockerfile",
                            Version = 1
                        },
                        new
                        {
                            Id = 15,
                            Architecture = "JavaScript",
                            Content = "version: '3.9'\nservices:\n  app:\n    build: .\n    ports:\n      - \"{{APP_PORT}}:3000\"\n    environment:\n      NODE_ENV: development\n      PORT: 3000\n      DATABASE_URL: postgres://postgres:secret@db:5432/{{DB_NAME}}\n    depends_on:\n      db:\n        condition: service_healthy\n\n  db:\n    image: postgres:16-alpine\n    environment:\n      POSTGRES_DB: {{DB_NAME}}\n      POSTGRES_PASSWORD: secret\n    ports:\n      - \"{{DB_PORT}}:5432\"\n    volumes:\n      - pgdata:/var/lib/postgresql/data\n    healthcheck:\n      test: [\"CMD\", \"pg_isready\", \"-U\", \"postgres\"]\n      interval: 10s\n      timeout: 5s\n      retries: 5\n\nvolumes:\n  pgdata:",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Database = "PostgreSQL",
                            Description = "Docker Compose para Node.js con PostgreSQL",
                            Infrastructure = "DockerCompose",
                            IsActive = true,
                            Name = "Compose JavaScript + PostgreSQL",
                            TemplateType = "compose",
                            Version = 1
                        },
                        new
                        {
                            Id = 16,
                            Architecture = "JavaScript",
                            Content = "version: '3.9'\nservices:\n  app:\n    build: .\n    ports:\n      - \"{{APP_PORT}}:3000\"\n    environment:\n      NODE_ENV: development\n      PORT: 3000\n      DATABASE_URL: mysql://root:secret@db:3306/{{DB_NAME}}\n    depends_on:\n      db:\n        condition: service_healthy\n\n  db:\n    image: mysql:8.0\n    environment:\n      MYSQL_ROOT_PASSWORD: secret\n      MYSQL_DATABASE: {{DB_NAME}}\n    ports:\n      - \"{{DB_PORT}}:3306\"\n    volumes:\n      - mysqldata:/var/lib/mysql\n    healthcheck:\n      test: [\"CMD\", \"mysqladmin\", \"ping\", \"-h\", \"localhost\"]\n      interval: 10s\n      timeout: 5s\n      retries: 5\n\nvolumes:\n  mysqldata:",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Database = "MySQL",
                            Description = "Docker Compose para Node.js con MySQL",
                            Infrastructure = "DockerCompose",
                            IsActive = true,
                            Name = "Compose JavaScript + MySQL",
                            TemplateType = "compose",
                            Version = 1
                        },
                        new
                        {
                            Id = 17,
                            Architecture = "JavaScript",
                            Content = "version: '3.9'\nservices:\n  app:\n    build: .\n    ports:\n      - \"{{APP_PORT}}:3000\"\n    environment:\n      NODE_ENV: development\n      PORT: 3000\n      DATABASE_URL: sqlite:///app/data/app.sqlite\n    volumes:\n      - sqlite-data:/app/data\n\nvolumes:\n  sqlite-data:",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Database = "SQLite",
                            Description = "Docker Compose para Node.js usando SQLite",
                            Infrastructure = "DockerCompose",
                            IsActive = true,
                            Name = "Compose JavaScript + SQLite",
                            TemplateType = "compose",
                            Version = 1
                        },
                        new
                        {
                            Id = 18,
                            Architecture = "JavaScript",
                            Content = "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: {{APP_NAME}}\nspec:\n  replicas: 2\n  selector:\n    matchLabels:\n      app: {{APP_NAME}}\n  template:\n    metadata:\n      labels:\n        app: {{APP_NAME}}\n    spec:\n      containers:\n        - name: {{APP_NAME}}\n          image: {{APP_NAME}}:latest\n          ports:\n            - containerPort: 3000\n          env:\n            - name: NODE_ENV\n              value: production\n---\napiVersion: v1\nkind: Service\nmetadata:\n  name: {{APP_NAME}}-svc\nspec:\n  selector:\n    app: {{APP_NAME}}\n  ports:\n    - port: 80\n      targetPort: 3000\n  type: LoadBalancer",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kubernetes Deployment y Service para Node.js",
                            Infrastructure = "Kubernetes",
                            IsActive = true,
                            Name = "K8s JavaScript Deployment",
                            TemplateType = "k8s-deployment",
                            Version = 1
                        },
                        new
                        {
                            Id = 19,
                            Architecture = "JavaScript",
                            Content = "name: CI\non:\n  push:\n    branches: [main]\n  pull_request:\n\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - name: Setup Node\n        uses: actions/setup-node@v4\n        with:\n          node-version: '22'\n          cache: npm\n      - name: Install dependencies\n        run: npm ci\n      - name: Build\n        run: npm run build --if-present\n      - name: Test\n        run: npm test --if-present",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pipeline CI/CD para Node.js, NestJS y Next.js",
                            IsActive = true,
                            Name = "CI JavaScript GitHub Actions",
                            TemplateType = "ci",
                            Version = 1
                        },
                        new
                        {
                            Id = 20,
                            Architecture = "JavaScript",
                            Content = "/node_modules/\n/dist/\n/.next/\n/.turbo/\n/coverage/\n/.env\n/.env.*\n/npm-debug.log*\n/yarn-debug.log*\n/pnpm-debug.log*",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gitignore base para proyectos Node.js modernos",
                            IsActive = true,
                            Name = "JavaScript .gitignore",
                            TemplateType = "gitignore",
                            Version = 1
                        });
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.VpsCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EncryptedPassword")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("PrivateKeyPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WizardConfigId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WizardConfigId");

                    b.ToTable("VpsCredentials");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.WizardConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalOptionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Architecture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Database")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeploymentTarget")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesignPatternsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Framework")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrameworkVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Infrastructure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LibrariesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("WizardConfigs");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.DesignPatternEntry", b =>
                {
                    b.HasOne("ProjectForge.Core.Entities.LibraryRecommendation", null)
                        .WithMany("SuggestedWithPatterns")
                        .HasForeignKey("LibraryRecommendationId");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.Project", b =>
                {
                    b.HasOne("ProjectForge.Core.Entities.ApplicationUser", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectForge.Core.Entities.WizardConfig", "WizardConfig")
                        .WithOne()
                        .HasForeignKey("ProjectForge.Core.Entities.Project", "WizardConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WizardConfig");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.ProjectLog", b =>
                {
                    b.HasOne("ProjectForge.Core.Entities.Project", "Project")
                        .WithMany("Logs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.VpsCredential", b =>
                {
                    b.HasOne("ProjectForge.Core.Entities.WizardConfig", "WizardConfig")
                        .WithMany("VpsCredentials")
                        .HasForeignKey("WizardConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WizardConfig");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.LibraryRecommendation", b =>
                {
                    b.Navigation("SuggestedWithPatterns");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.Project", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.WizardConfig", b =>
                {
                    b.Navigation("VpsCredentials");
                });
#pragma warning restore 612, 618
        }
    }
}
