// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectForge.Infrastructure.Data;

#nullable disable

namespace ProjectForge.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectForge.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GitHubId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GitHubId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.DesignPatternEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Architecture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImplementationNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LibraryRecommendationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScaffoldCommandsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LibraryRecommendationId");

                    b.ToTable("DesignPatterns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Architecture = "DotNet",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Abstrae el acceso a datos detrás de interfaces, facilitando testing y mantenimiento.",
                            Name = "Repository Pattern",
                            Pattern = "Repository"
                        },
                        new
                        {
                            Id = 2,
                            Architecture = "DotNet",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Separa las operaciones de lectura (Queries) de las de escritura (Commands).",
                            Name = "CQRS",
                            Pattern = "CQRS"
                        },
                        new
                        {
                            Id = 3,
                            Architecture = "DotNet",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Arquitectura en capas concéntricas con dependencias hacia el centro.",
                            Name = "Clean Architecture",
                            Pattern = "CleanArchitecture"
                        },
                        new
                        {
                            Id = 4,
                            Architecture = "DotNet",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Reduce el acoplamiento directo entre componentes usando un mediador.",
                            Name = "Mediator",
                            Pattern = "Mediator"
                        },
                        new
                        {
                            Id = 5,
                            Architecture = "Python",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Patrón de repositorio adaptado para Python/FastAPI.",
                            Name = "Repository Pattern",
                            Pattern = "Repository"
                        },
                        new
                        {
                            Id = 6,
                            Architecture = "JavaScript",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Arquitectura de microservicios para aplicaciones Node.js.",
                            Name = "Microservices",
                            Pattern = "Microservices"
<<<<<<< HEAD
=======
                        },
                        new
                        {
                            Id = 7,
                            Architecture = "Java",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Patrón de repositorio con Spring Data JPA para Java.",
                            Name = "Repository Pattern",
                            Pattern = "Repository"
                        },
                        new
                        {
                            Id = 8,
                            Architecture = "Java",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Separación de comandos y consultas en aplicaciones Spring Boot.",
                            Name = "CQRS",
                            Pattern = "CQRS"
                        },
                        new
                        {
                            Id = 9,
                            Architecture = "Java",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ports & Adapters: aísla el dominio de la infraestructura. Muy usado en Java empresarial.",
                            Name = "Hexagonal Architecture",
                            Pattern = "HexagonalArchitecture"
                        },
                        new
                        {
                            Id = 10,
                            Architecture = "Java",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Arquitectura de microservicios con Spring Boot y Spring Cloud.",
                            Name = "Microservices",
                            Pattern = "Microservices"
                        },
                        new
                        {
                            Id = 11,
                            Architecture = "Python",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Capas bien definidas (domain, application, infrastructure) para proyectos Python.",
                            Name = "Clean Architecture",
                            Pattern = "CleanArchitecture"
                        },
                        new
                        {
                            Id = 12,
                            Architecture = "TypeScript",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Aísla el dominio de la infraestructura con puertos y adaptadores. Ideal para NestJS.",
                            Name = "Hexagonal Architecture (Ports & Adapters)",
                            Pattern = "HexagonalArchitecture"
                        },
                        new
                        {
                            Id = 13,
                            Architecture = "TypeScript",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Organización basada en componentes reutilizables, clave en Next.js y NestJS.",
                            Name = "Component-Based Architecture",
                            Pattern = "Repository"
                        },
                        new
                        {
                            Id = 14,
                            Architecture = "TypeScript",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Comunicación reactiva entre componentes desacoplados usando observadores.",
                            Name = "Observer Pattern",
                            Pattern = "MVVM"
                        },
                        new
                        {
                            Id = 15,
                            Architecture = "TypeScript",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Centraliza la comunicación entre módulos TypeScript evitando dependencias directas.",
                            Name = "Mediator Pattern",
                            Pattern = "Mediator"
                        },
                        new
                        {
                            Id = 16,
                            Architecture = "TypeScript",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Aplicación de los 5 principios SOLID al diseño de módulos TypeScript/NestJS.",
                            Name = "SOLID Principles Integration",
                            Pattern = "CleanArchitecture"
>>>>>>> 0dc2a35 (complete java,python,typescript)
                        });
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.LibraryRecommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Architecture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Framework")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstallCommand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PopularityScore")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Libraries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Architecture = "DotNet",
                            Category = "CQRS/Mediator",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Implementación del patrón Mediator para CQRS",
                            Framework = "AspNetCoreWebApi",
                            InstallCommand = "dotnet add package MediatR",
                            Name = "MediatR",
                            PackageName = "MediatR",
                            PopularityScore = 95
                        },
                        new
                        {
                            Id = 2,
                            Architecture = "DotNet",
                            Category = "ORM",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "ORM oficial de Microsoft para .NET",
                            Framework = "AspNetCoreWebApi",
                            InstallCommand = "dotnet add package Microsoft.EntityFrameworkCore",
                            Name = "Entity Framework Core",
                            PackageName = "Microsoft.EntityFrameworkCore",
                            PopularityScore = 99
                        },
                        new
                        {
                            Id = 3,
                            Architecture = "DotNet",
                            Category = "Validation",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Validación fluida y expresiva",
                            InstallCommand = "dotnet add package FluentValidation.AspNetCore",
                            Name = "FluentValidation",
                            PackageName = "FluentValidation.AspNetCore",
                            PopularityScore = 92
                        },
                        new
                        {
                            Id = 4,
                            Architecture = "DotNet",
                            Category = "Logging",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Logging estructurado para .NET",
                            InstallCommand = "dotnet add package Serilog.AspNetCore",
                            Name = "Serilog",
                            PackageName = "Serilog.AspNetCore",
                            PopularityScore = 97
                        },
                        new
                        {
                            Id = 5,
                            Architecture = "DotNet",
                            Category = "Mapping",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mapeo automático entre objetos",
                            InstallCommand = "dotnet add package AutoMapper",
                            Name = "AutoMapper",
                            PackageName = "AutoMapper",
                            PopularityScore = 94
                        },
                        new
                        {
                            Id = 6,
                            Architecture = "DotNet",
                            Category = "Documentation",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Generación automática de documentación OpenAPI",
                            Framework = "AspNetCoreWebApi",
                            InstallCommand = "dotnet add package Swashbuckle.AspNetCore",
                            Name = "Swashbuckle (Swagger)",
                            PackageName = "Swashbuckle.AspNetCore",
                            PopularityScore = 98
                        },
                        new
                        {
                            Id = 7,
                            Architecture = "DotNet",
                            Category = "Testing",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Framework de testing unitario para .NET",
                            InstallCommand = "dotnet add package xunit",
                            Name = "xUnit",
                            PackageName = "xunit",
                            PopularityScore = 96
                        },
                        new
                        {
                            Id = 8,
                            Architecture = "Python",
                            Category = "ORM",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "ORM más popular para Python",
                            InstallCommand = "pip install sqlalchemy",
                            Name = "SQLAlchemy",
                            PackageName = "sqlalchemy",
                            PopularityScore = 98
                        },
                        new
                        {
                            Id = 9,
                            Architecture = "Python",
                            Category = "Validation",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Validación de datos con type hints",
                            InstallCommand = "pip install pydantic",
                            Name = "Pydantic",
                            PackageName = "pydantic",
                            PopularityScore = 97
                        },
                        new
                        {
                            Id = 10,
                            Architecture = "Python",
                            Category = "Migrations",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Migraciones de base de datos para SQLAlchemy",
                            InstallCommand = "pip install alembic",
                            Name = "Alembic",
                            PackageName = "alembic",
                            PopularityScore = 90
<<<<<<< HEAD
=======
                        },
                        new
                        {
                            Id = 11,
                            Architecture = "Python",
                            Category = "Testing",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Framework de testing para Python",
                            InstallCommand = "pip install pytest",
                            Name = "pytest",
                            PackageName = "pytest",
                            PopularityScore = 98
                        },
                        new
                        {
                            Id = 12,
                            Architecture = "Python",
                            Category = "HTTP Client",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cliente HTTP async para tests e integraciones",
                            InstallCommand = "pip install httpx",
                            Name = "httpx",
                            PackageName = "httpx",
                            PopularityScore = 88
                        },
                        new
                        {
                            Id = 13,
                            Architecture = "Python",
                            Category = "Config",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Carga variables de entorno desde .env",
                            InstallCommand = "pip install python-dotenv",
                            Name = "python-dotenv",
                            PackageName = "python-dotenv",
                            PopularityScore = 95
                        },
                        new
                        {
                            Id = 14,
                            Architecture = "Java",
                            Category = "ORM",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Repositorios JPA con Spring Data",
                            Framework = "SpringBoot",
                            InstallCommand = "mvn dependency:get -Dartifact=org.springframework.boot:spring-boot-starter-data-jpa",
                            Name = "Spring Data JPA",
                            PackageName = "org.springframework.boot:spring-boot-starter-data-jpa",
                            PopularityScore = 99
                        },
                        new
                        {
                            Id = 15,
                            Architecture = "Java",
                            Category = "Security",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Autenticación y autorización para Spring Boot",
                            Framework = "SpringBoot",
                            InstallCommand = "mvn dependency:get -Dartifact=org.springframework.boot:spring-boot-starter-security",
                            Name = "Spring Security",
                            PackageName = "org.springframework.boot:spring-boot-starter-security",
                            PopularityScore = 97
                        },
                        new
                        {
                            Id = 16,
                            Architecture = "Java",
                            Category = "Mapping",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mapeo entre objetos Java en tiempo de compilación",
                            InstallCommand = "mvn dependency:get -Dartifact=org.mapstruct:mapstruct:1.5.5.Final",
                            Name = "MapStruct",
                            PackageName = "org.mapstruct:mapstruct",
                            PopularityScore = 91
                        },
                        new
                        {
                            Id = 17,
                            Architecture = "Java",
                            Category = "Boilerplate",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Reduce boilerplate con anotaciones (@Getter, @Builder...)",
                            InstallCommand = "mvn dependency:get -Dartifact=org.projectlombok:lombok:1.18.32",
                            Name = "Lombok",
                            PackageName = "org.projectlombok:lombok",
                            PopularityScore = 98
                        },
                        new
                        {
                            Id = 18,
                            Architecture = "Java",
                            Category = "Documentation",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Swagger UI / OpenAPI 3 para Spring Boot 3",
                            Framework = "SpringBoot",
                            InstallCommand = "mvn dependency:get -Dartifact=org.springdoc:springdoc-openapi-starter-webmvc-ui:2.5.0",
                            Name = "springdoc-openapi",
                            PackageName = "org.springdoc:springdoc-openapi-starter-webmvc-ui",
                            PopularityScore = 93
                        },
                        new
                        {
                            Id = 19,
                            Architecture = "Java",
                            Category = "Testing",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Framework de testing unitario para Java",
                            InstallCommand = "mvn dependency:get -Dartifact=org.junit.jupiter:junit-jupiter:5.10.0",
                            Name = "JUnit 5",
                            PackageName = "org.junit.jupiter:junit-jupiter",
                            PopularityScore = 99
                        },
                        new
                        {
                            Id = 20,
                            Architecture = "Java",
                            Category = "Migrations",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Migraciones de base de datos para Java",
                            InstallCommand = "mvn dependency:get -Dartifact=org.flywaydb:flyway-core:10.0.0",
                            Name = "Flyway",
                            PackageName = "org.flywaydb:flyway-core",
                            PopularityScore = 92
                        },
                        new
                        {
                            Id = 21,
                            Architecture = "TypeScript",
                            Category = "Validation",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Validación de esquemas con inferencia de tipos TypeScript",
                            InstallCommand = "npm install zod",
                            Name = "Zod",
                            PackageName = "zod",
                            PopularityScore = 97
                        },
                        new
                        {
                            Id = 22,
                            Architecture = "TypeScript",
                            Category = "ORM",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "ORM moderno con tipado automático para TypeScript/Node.js",
                            InstallCommand = "npm install prisma @prisma/client",
                            Name = "Prisma",
                            PackageName = "prisma",
                            PopularityScore = 96
                        },
                        new
                        {
                            Id = 23,
                            Architecture = "TypeScript",
                            Category = "ORM",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "ORM basado en decoradores, nativo para TypeScript y NestJS",
                            InstallCommand = "npm install typeorm reflect-metadata",
                            Name = "TypeORM",
                            PackageName = "typeorm",
                            PopularityScore = 91
                        },
                        new
                        {
                            Id = 24,
                            Architecture = "TypeScript",
                            Category = "Testing",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Framework de testing rápido con soporte nativo para TypeScript",
                            InstallCommand = "npm install --save-dev jest ts-jest @types/jest",
                            Name = "Jest",
                            PackageName = "jest",
                            PopularityScore = 98
                        },
                        new
                        {
                            Id = 25,
                            Architecture = "TypeScript",
                            Category = "Reactive",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Librería para programación reactiva y manejo de streams",
                            InstallCommand = "npm install rxjs",
                            Name = "RxJS",
                            PackageName = "rxjs",
                            PopularityScore = 94
                        },
                        new
                        {
                            Id = 26,
                            Architecture = "TypeScript",
                            Category = "Validation",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Decoradores de validación para clases TypeScript (ideal NestJS)",
                            InstallCommand = "npm install class-validator class-transformer",
                            Name = "class-validator",
                            PackageName = "class-validator",
                            PopularityScore = 93
                        },
                        new
                        {
                            Id = 27,
                            Architecture = "TypeScript",
                            Category = "Config",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Carga variables de entorno desde .env en Node.js/TypeScript",
                            InstallCommand = "npm install dotenv",
                            Name = "dotenv",
                            PackageName = "dotenv",
                            PopularityScore = 99
>>>>>>> 0dc2a35 (complete java,python,typescript)
                        });
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneratedReadme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepositoryUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WizardConfigId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WizardConfigId")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.ProjectLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommandExecuted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("int");

                    b.Property<bool>("IsError")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectLogs");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.ProjectTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Architecture")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Database")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Framework")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Infrastructure")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VariablesSchemaJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Architecture", "TemplateType", "Database", "Infrastructure");

                    b.ToTable("Templates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Architecture = "DotNet",
                            Content = "FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base\nWORKDIR /app\nEXPOSE 8080\n\nFROM mcr.microsoft.com/dotnet/sdk:10.0 AS build\nWORKDIR /src\nCOPY . .\nRUN dotnet restore\nRUN dotnet publish -c Release -o /app/publish\n\nFROM base AS final\nWORKDIR /app\nCOPY --from=build /app/publish .\nENTRYPOINT [\"dotnet\", \"{{APP_NAME}}.dll\"]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Multi-stage Dockerfile para ASP.NET Core",
                            IsActive = true,
                            Name = "Dockerfile .NET",
                            TemplateType = "dockerfile",
                            Version = 1
                        },
                        new
                        {
                            Id = 2,
                            Architecture = "DotNet",
                            Content = "version: '3.9'\nservices:\n  app:\n    build: .\n    ports:\n      - \"{{APP_PORT}}:8080\"\n    environment:\n      - ConnectionStrings__Default=Host=db;Database={{DB_NAME}};Username=postgres;Password=secret\n    depends_on:\n      db:\n        condition: service_healthy\n\n  db:\n    image: postgres:16-alpine\n    environment:\n      POSTGRES_DB: {{DB_NAME}}\n      POSTGRES_PASSWORD: secret\n    ports:\n      - \"{{DB_PORT}}:5432\"\n    volumes:\n      - pgdata:/var/lib/postgresql/data\n    healthcheck:\n      test: [\"CMD\",\"pg_isready\",\"-U\",\"postgres\"]\n      interval: 10s\n      timeout: 5s\n      retries: 5\n\nvolumes:\n  pgdata:",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Database = "PostgreSQL",
                            Description = "Docker Compose para .NET + PostgreSQL",
                            Infrastructure = "DockerCompose",
                            IsActive = true,
                            Name = "Compose .NET + PostgreSQL",
                            TemplateType = "compose",
                            Version = 1
                        },
                        new
                        {
                            Id = 3,
                            Architecture = "DotNet",
                            Content = "version: '3.9'\nservices:\n  app:\n    build: .\n    ports:\n      - \"{{APP_PORT}}:8080\"\n    environment:\n      - ConnectionStrings__Default=Server=db;Database={{DB_NAME}};User=root;Password=secret;\n    depends_on:\n      db:\n        condition: service_healthy\n\n  db:\n    image: mysql:8.0\n    environment:\n      MYSQL_ROOT_PASSWORD: secret\n      MYSQL_DATABASE: {{DB_NAME}}\n    ports:\n      - \"{{DB_PORT}}:3306\"\n    volumes:\n      - mysqldata:/var/lib/mysql\n    healthcheck:\n      test: [\"CMD\",\"mysqladmin\",\"ping\",\"-h\",\"localhost\"]\n      interval: 10s\n      timeout: 5s\n      retries: 5\n\nvolumes:\n  mysqldata:",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Database = "MySQL",
                            Description = "Docker Compose para .NET + MySQL",
                            Infrastructure = "DockerCompose",
                            IsActive = true,
                            Name = "Compose .NET + MySQL",
                            TemplateType = "compose",
                            Version = 1
                        },
                        new
                        {
                            Id = 4,
                            Architecture = "DotNet",
                            Content = "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: {{APP_NAME}}\nspec:\n  replicas: 2\n  selector:\n    matchLabels:\n      app: {{APP_NAME}}\n  template:\n    metadata:\n      labels:\n        app: {{APP_NAME}}\n    spec:\n      containers:\n      - name: {{APP_NAME}}\n        image: {{APP_NAME}}:latest\n        ports:\n        - containerPort: 8080\n---\napiVersion: v1\nkind: Service\nmetadata:\n  name: {{APP_NAME}}-svc\nspec:\n  selector:\n    app: {{APP_NAME}}\n  ports:\n  - port: 80\n    targetPort: 8080\n  type: LoadBalancer",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kubernetes Deployment para la aplicación",
                            Infrastructure = "Kubernetes",
                            IsActive = true,
                            Name = "K8s App Deployment",
                            TemplateType = "k8s-deployment",
                            Version = 1
                        },
                        new
                        {
                            Id = 5,
                            Architecture = "DotNet",
                            Content = "[Dd]ebug/\n[Rr]elease/\n[Bb]in/\n[Oo]bj/\n*.user\n*.suo\n*.vs/\n.vscode/\n.env\n.env.*\n*.pfx\npackages/",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gitignore para proyectos .NET",
                            IsActive = true,
                            Name = ".gitignore .NET",
                            TemplateType = "gitignore",
                            Version = 1
                        },
                        new
                        {
                            Id = 6,
                            Architecture = "DotNet",
                            Content = "name: CI/CD\non:\n  push:\n    branches: [main]\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n    - uses: actions/checkout@v4\n    - uses: actions/setup-dotnet@v4\n      with:\n        dotnet-version: '10.0.x'\n    - run: dotnet restore\n    - run: dotnet build --no-restore\n    - run: dotnet test --no-build",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pipeline CI/CD para .NET con GitHub Actions",
                            IsActive = true,
                            Name = "CI .NET GitHub Actions",
                            TemplateType = "ci",
                            Version = 1
<<<<<<< HEAD
=======
                        },
                        new
                        {
                            Id = 7,
                            Architecture = "Java",
                            Content = "FROM eclipse-temurin:21-jdk-alpine AS build\nWORKDIR /app\nCOPY . .\nRUN ./mvnw -q package -DskipTests\n\nFROM eclipse-temurin:21-jre-alpine AS final\nWORKDIR /app\nCOPY --from=build /app/target/*.jar app.jar\nEXPOSE 8080\nENTRYPOINT [\"java\",\"-jar\",\"app.jar\"]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Multi-stage Dockerfile para Spring Boot con Maven",
                            IsActive = true,
                            Name = "Dockerfile Java Spring Boot",
                            TemplateType = "dockerfile",
                            Version = 1
                        },
                        new
                        {
                            Id = 8,
                            Architecture = "Java",
                            Content = "version: '3.9'\nservices:\n  app:\n    build: .\n    ports:\n      - \"{{APP_PORT}}:8080\"\n    environment:\n      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/{{DB_NAME}}\n      - SPRING_DATASOURCE_USERNAME=postgres\n      - SPRING_DATASOURCE_PASSWORD=secret\n      - SPRING_JPA_HIBERNATE_DDL_AUTO=update\n    depends_on:\n      db:\n        condition: service_healthy\n\n  db:\n    image: postgres:16-alpine\n    environment:\n      POSTGRES_DB: {{DB_NAME}}\n      POSTGRES_PASSWORD: secret\n    ports:\n      - \"{{DB_PORT}}:5432\"\n    volumes:\n      - pgdata:/var/lib/postgresql/data\n    healthcheck:\n      test: [\"CMD\",\"pg_isready\",\"-U\",\"postgres\"]\n      interval: 10s\n      timeout: 5s\n      retries: 5\n\nvolumes:\n  pgdata:",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Database = "PostgreSQL",
                            Description = "Docker Compose para Spring Boot + PostgreSQL",
                            Infrastructure = "DockerCompose",
                            IsActive = true,
                            Name = "Compose Java + PostgreSQL",
                            TemplateType = "compose",
                            Version = 1
                        },
                        new
                        {
                            Id = 9,
                            Architecture = "Java",
                            Content = "version: '3.9'\nservices:\n  app:\n    build: .\n    ports:\n      - \"{{APP_PORT}}:8080\"\n    environment:\n      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/{{DB_NAME}}\n      - SPRING_DATASOURCE_USERNAME=root\n      - SPRING_DATASOURCE_PASSWORD=secret\n      - SPRING_JPA_HIBERNATE_DDL_AUTO=update\n    depends_on:\n      db:\n        condition: service_healthy\n\n  db:\n    image: mysql:8.0\n    environment:\n      MYSQL_ROOT_PASSWORD: secret\n      MYSQL_DATABASE: {{DB_NAME}}\n    ports:\n      - \"{{DB_PORT}}:3306\"\n    volumes:\n      - mysqldata:/var/lib/mysql\n    healthcheck:\n      test: [\"CMD\",\"mysqladmin\",\"ping\",\"-h\",\"localhost\"]\n      interval: 10s\n      timeout: 5s\n      retries: 5\n\nvolumes:\n  mysqldata:",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Database = "MySQL",
                            Description = "Docker Compose para Spring Boot + MySQL",
                            Infrastructure = "DockerCompose",
                            IsActive = true,
                            Name = "Compose Java + MySQL",
                            TemplateType = "compose",
                            Version = 1
                        },
                        new
                        {
                            Id = 10,
                            Architecture = "Java",
                            Content = "target/\n*.class\n*.jar\n*.war\n*.ear\n.mvn/\n!.mvn/wrapper/\n.idea/\n*.iml\n.vscode/\n.env\n.env.*\n*.log\nspring-shell.log\nmvnw\n!mvnw\nmvnw.cmd\n!mvnw.cmd",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gitignore para proyectos Java/Maven/Spring Boot",
                            IsActive = true,
                            Name = ".gitignore Java",
                            TemplateType = "gitignore",
                            Version = 1
                        },
                        new
                        {
                            Id = 11,
                            Architecture = "Java",
                            Content = "name: CI/CD\non:\n  push:\n    branches: [main]\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n    - uses: actions/checkout@v4\n    - uses: actions/setup-java@v4\n      with:\n        java-version: '21'\n        distribution: 'temurin'\n        cache: maven\n    - run: ./mvnw -q verify\n    - name: Build Docker image\n      run: docker build -t {{APP_NAME}}:latest .",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pipeline CI/CD para Java + Maven con GitHub Actions",
                            IsActive = true,
                            Name = "CI Java GitHub Actions",
                            TemplateType = "ci",
                            Version = 1
                        },
                        new
                        {
                            Id = 12,
                            Architecture = "Python",
                            Content = "FROM python:3.12-slim AS base\nWORKDIR /app\n\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\n\nCOPY . .\nEXPOSE 8080\n\nCMD [\"uvicorn\", \"main:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8080\"]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dockerfile para FastAPI/Flask con Python 3.12",
                            IsActive = true,
                            Name = "Dockerfile Python FastAPI",
                            TemplateType = "dockerfile",
                            Version = 1
                        },
                        new
                        {
                            Id = 13,
                            Architecture = "Python",
                            Content = "version: '3.9'\nservices:\n  app:\n    build: .\n    ports:\n      - \"{{APP_PORT}}:8080\"\n    environment:\n      - DATABASE_URL=postgresql://postgres:secret@db:5432/{{DB_NAME}}\n      - DEBUG=False\n    depends_on:\n      db:\n        condition: service_healthy\n    volumes:\n      - .:/app\n\n  db:\n    image: postgres:16-alpine\n    environment:\n      POSTGRES_DB: {{DB_NAME}}\n      POSTGRES_PASSWORD: secret\n    ports:\n      - \"{{DB_PORT}}:5432\"\n    volumes:\n      - pgdata:/var/lib/postgresql/data\n    healthcheck:\n      test: [\"CMD\",\"pg_isready\",\"-U\",\"postgres\"]\n      interval: 10s\n      timeout: 5s\n      retries: 5\n\nvolumes:\n  pgdata:",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Database = "PostgreSQL",
                            Description = "Docker Compose para FastAPI/Django + PostgreSQL",
                            Infrastructure = "DockerCompose",
                            IsActive = true,
                            Name = "Compose Python + PostgreSQL",
                            TemplateType = "compose",
                            Version = 1
                        },
                        new
                        {
                            Id = 14,
                            Architecture = "Python",
                            Content = "version: '3.9'\nservices:\n  app:\n    build: .\n    ports:\n      - \"{{APP_PORT}}:8080\"\n    environment:\n      - DATABASE_URL=mysql+pymysql://root:secret@db:3306/{{DB_NAME}}\n    depends_on:\n      db:\n        condition: service_healthy\n    volumes:\n      - .:/app\n\n  db:\n    image: mysql:8.0\n    environment:\n      MYSQL_ROOT_PASSWORD: secret\n      MYSQL_DATABASE: {{DB_NAME}}\n    ports:\n      - \"{{DB_PORT}}:3306\"\n    volumes:\n      - mysqldata:/var/lib/mysql\n    healthcheck:\n      test: [\"CMD\",\"mysqladmin\",\"ping\",\"-h\",\"localhost\"]\n      interval: 10s\n      timeout: 5s\n      retries: 5\n\nvolumes:\n  mysqldata:",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Database = "MySQL",
                            Description = "Docker Compose para FastAPI/Django + MySQL",
                            Infrastructure = "DockerCompose",
                            IsActive = true,
                            Name = "Compose Python + MySQL",
                            TemplateType = "compose",
                            Version = 1
                        },
                        new
                        {
                            Id = 15,
                            Architecture = "Python",
                            Content = "__pycache__/\n*.py[cod]\n*.pyo\n.env\n.env.*\nvenv/\n.venv/\n*.egg-info/\ndist/\nbuild/\n.pytest_cache/\n.mypy_cache/\n.coverage\nhtmlcov/\n*.sqlite3\n.vscode/\n.idea/",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gitignore para proyectos Python",
                            IsActive = true,
                            Name = ".gitignore Python",
                            TemplateType = "gitignore",
                            Version = 1
                        },
                        new
                        {
                            Id = 16,
                            Architecture = "Python",
                            Content = "name: CI/CD\non:\n  push:\n    branches: [main]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n    - uses: actions/checkout@v4\n    - uses: actions/setup-python@v5\n      with:\n        python-version: '3.12'\n        cache: pip\n    - run: pip install -r requirements.txt\n    - run: python -m pytest tests/ -v\n    - name: Build Docker image\n      run: docker build -t {{APP_NAME}}:latest .",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pipeline CI/CD para Python con GitHub Actions",
                            IsActive = true,
                            Name = "CI Python GitHub Actions",
                            TemplateType = "ci",
                            Version = 1
>>>>>>> 0dc2a35 (complete java,python,typescript)
                        });
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.VpsCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EncryptedPassword")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("PrivateKeyPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WizardConfigId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WizardConfigId");

                    b.ToTable("VpsCredentials");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.WizardConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalOptionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Architecture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Database")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeploymentTarget")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesignPatternsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Framework")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrameworkVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Infrastructure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LibrariesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("WizardConfigs");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.DesignPatternEntry", b =>
                {
                    b.HasOne("ProjectForge.Core.Entities.LibraryRecommendation", null)
                        .WithMany("SuggestedWithPatterns")
                        .HasForeignKey("LibraryRecommendationId");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.Project", b =>
                {
                    b.HasOne("ProjectForge.Core.Entities.ApplicationUser", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectForge.Core.Entities.WizardConfig", "WizardConfig")
                        .WithOne()
                        .HasForeignKey("ProjectForge.Core.Entities.Project", "WizardConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WizardConfig");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.ProjectLog", b =>
                {
                    b.HasOne("ProjectForge.Core.Entities.Project", "Project")
                        .WithMany("Logs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.VpsCredential", b =>
                {
                    b.HasOne("ProjectForge.Core.Entities.WizardConfig", "WizardConfig")
                        .WithMany("VpsCredentials")
                        .HasForeignKey("WizardConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WizardConfig");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.LibraryRecommendation", b =>
                {
                    b.Navigation("SuggestedWithPatterns");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.Project", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.WizardConfig", b =>
                {
                    b.Navigation("VpsCredentials");
                });

            modelBuilder.Entity("ProjectForge.Core.Entities.AiSuggestionCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CacheKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PatternsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LibrariesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CacheKey")
                        .IsUnique();

                    b.ToTable("AiSuggestionCaches");
                });

#pragma warning restore 612, 618
        }
    }
}
