<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.*">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Octokit" Version="9.*" />
    <PackageReference Include="SSH.NET" Version="2024.*" />
    <ProjectReference Include="..\ProjectForge.Core\ProjectForge.Core.csproj" />
    <ProjectReference Include="..\ProjectForge.Application\ProjectForge.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Migrations\" />
    <Folder Include="Seeders\" />
  </ItemGroup>
</Project>
