using ProjectForge.Application.UseCases.Projects;
using ProjectForge.Core.Entities;
using ProjectForge.Core.Interfaces;
using Xunit;

namespace ProjectForge.Application.Tests;

public class CreateProjectUseCaseTests
{
    [Fact]
    public async Task ExecuteAsync_persists_a_project_with_the_expected_values()
    {
        var repository = new FakeProjectRepository();
        var useCase = new CreateProjectUseCase(repository);

        var result = await useCase.ExecuteAsync(
            new CreateProjectRequest(7, 11, "Project Forge", "Generated by wizard"));

        Assert.Equal(1, repository.AddCalls);
        Assert.NotNull(result);
        Assert.Equal(101, result.Id);
        Assert.Equal(7, result.UserId);
        Assert.Equal(11, result.WizardConfigId);
        Assert.Equal("Project Forge", result.Name);
        Assert.Equal("Generated by wizard", result.Description);
        Assert.Same(repository.StoredProject, result);
    }

    [Fact]
    public async Task ExecuteAsync_rejects_invalid_project_name_before_persisting()
    {
        var repository = new FakeProjectRepository();
        var useCase = new CreateProjectUseCase(repository);

        await Assert.ThrowsAsync<ProjectForge.Core.Exceptions.DomainException>(() =>
            useCase.ExecuteAsync(new CreateProjectRequest(7, 11, "ab", null)));

        Assert.Equal(0, repository.AddCalls);
        Assert.Null(repository.StoredProject);
    }

    private sealed class FakeProjectRepository : IProjectRepository
    {
        public int AddCalls { get; private set; }
        public Project? StoredProject { get; private set; }

        public Task<Project?> GetByIdAsync(int id) => Task.FromResult<Project?>(null);
        public Task<IEnumerable<Project>> GetAllAsync() => Task.FromResult<IEnumerable<Project>>(Array.Empty<Project>());
        public Task<Project> AddAsync(Project entity)
        {
            AddCalls++;
            entity.Id = 101;
            StoredProject = entity;
            return Task.FromResult(entity);
        }
        public Task UpdateAsync(Project entity) => Task.CompletedTask;
        public Task DeleteAsync(int id) => Task.CompletedTask;
        public Task<IEnumerable<Project>> GetByUserIdAsync(int userId) => Task.FromResult<IEnumerable<Project>>(Array.Empty<Project>());
        public Task<Project?> GetWithLogsAsync(int projectId) => Task.FromResult<Project?>(null);
        public Task<Project?> GetFullAsync(int projectId) => Task.FromResult<Project?>(null);
    }
}
